# Generated by Django 3.2.16 on 2023-03-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_rename_name_tablebooking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablebooking',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
