# Generated by Django 3.2.16 on 2023-02-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tavern', '0004_alter_review_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.IntegerField(choices=[(0, 'Hidden'), (1, 'Shown')], default=0),
        ),
    ]
